[2022-08-30 14:48:55,839] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 14:48:55,849] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 14:48:55,850] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 14:48:55,850] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-30 14:48:55,850] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 14:48:55,867] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-08-29 00:00:00+00:00
[2022-08-30 14:48:55,873] {standard_task_runner.py:52} INFO - Started process 101 to run task
[2022-08-30 14:48:55,879] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfyvtyau9', '--error-file', '/tmp/tmpy71ak9y5']
[2022-08-30 14:48:55,880] {standard_task_runner.py:80} INFO - Job 112: Subtask is_api_available
[2022-08-30 14:48:55,959] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-08-29T00:00:00+00:00 [running]> on host 7f0ff65cfbf7
[2022-08-30 14:48:56,064] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2022-08-30 14:48:56,065] {http.py:97} INFO - Poking: api/
[2022-08-30 14:48:56,079] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-08-30 14:48:56,081] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-08-30 14:48:57,540] {base.py:301} INFO - Success criteria met. Exiting.
[2022-08-30 14:48:57,558] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220829T000000, start_date=20220830T144855, end_date=20220830T144857
[2022-08-30 14:48:57,616] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-30 14:48:57,686] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
