[2022-08-30 14:48:52,569] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_user scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 14:48:52,617] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_user scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 14:48:52,618] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 14:48:52,618] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-30 14:48:52,618] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 14:48:52,721] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_user> on 2022-08-29 00:00:00+00:00
[2022-08-30 14:48:52,744] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_user', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbklll7u0', '--error-file', '/tmp/tmpmjslo4_f']
[2022-08-30 14:48:52,754] {standard_task_runner.py:80} INFO - Job 110: Subtask create_user
[2022-08-30 14:48:52,759] {standard_task_runner.py:52} INFO - Started process 95 to run task
[2022-08-30 14:48:53,019] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_user scheduled__2022-08-29T00:00:00+00:00 [running]> on host 7f0ff65cfbf7
[2022-08-30 14:48:53,322] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2022-08-30 14:48:53,414] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-30 14:48:53,424] {dbapi.py:208} INFO - Running statement: 
        create table if not exists users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-08-30 14:48:53,434] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-08-30 14:48:53,472] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_user, execution_date=20220829T000000, start_date=20220830T144852, end_date=20220830T144853
[2022-08-30 14:48:53,540] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-30 14:48:53,638] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
