[2022-08-29 16:19:59,328] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_user scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 16:19:59,339] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_user scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 16:19:59,339] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 16:19:59,339] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-29 16:19:59,339] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 16:19:59,360] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_user> on 2022-08-28 00:00:00+00:00
[2022-08-29 16:19:59,367] {standard_task_runner.py:52} INFO - Started process 3246 to run task
[2022-08-29 16:19:59,374] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_user', 'scheduled__2022-08-28T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpffu3ffh4', '--error-file', '/tmp/tmpfx0hcwmg']
[2022-08-29 16:19:59,375] {standard_task_runner.py:80} INFO - Job 98: Subtask create_user
[2022-08-29 16:19:59,462] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_user scheduled__2022-08-28T00:00:00+00:00 [running]> on host 7f0ff65cfbf7
[2022-08-29 16:19:59,584] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-28T00:00:00+00:00
[2022-08-29 16:19:59,597] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-29 16:19:59,602] {dbapi.py:208} INFO - Running statement: 
        create table if not exists users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2022-08-29 16:19:59,603] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-08-29 16:19:59,620] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_user, execution_date=20220828T000000, start_date=20220829T161959, end_date=20220829T161959
[2022-08-29 16:19:59,666] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-29 16:19:59,735] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
