[2022-08-30 14:49:02,457] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 14:49:02,470] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2022-08-30 14:49:02,471] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 14:49:02,471] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-30 14:49:02,471] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-30 14:49:02,490] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_user> on 2022-08-29 00:00:00+00:00
[2022-08-30 14:49:02,496] {standard_task_runner.py:52} INFO - Started process 119 to run task
[2022-08-30 14:49:02,501] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptfb93i5s', '--error-file', '/tmp/tmp3o262_z1']
[2022-08-30 14:49:02,503] {standard_task_runner.py:80} INFO - Job 115: Subtask store_user
[2022-08-30 14:49:02,584] {task_command.py:369} INFO - Running <TaskInstance: user_processing.store_user scheduled__2022-08-29T00:00:00+00:00 [running]> on host 7f0ff65cfbf7
[2022-08-30 14:49:02,687] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2022-08-30 14:49:02,690] {postgres.py:127} INFO - Running copy expert: COPY users from stdin WITH DELIMITER AS ',', filename: /tmp/processed_user.csv
[2022-08-30 14:49:02,701] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-30 14:49:02,731] {python.py:173} INFO - Done. Returned value was: None
[2022-08-30 14:49:02,750] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20220829T000000, start_date=20220830T144902, end_date=20220830T144902
[2022-08-30 14:49:02,794] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-30 14:49:02,839] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
